[pytest]
markers =
    smoke: Smoke test suite
    regression: Regression test suite
    ui: UI test cases
    login: Login test cases
    notes : Notes related test cases
    api: API test cases
    e2e: End to end hybrid test cases
